FROM maven:3.8.6-eclipse-temurin-17-alpine AS build
COPY src /tmp/src
COPY pom.xml /tmp/pom.xml
WORKDIR /tmp
RUN mvn clean package

FROM eclipse-temurin:17-jdk-alpine
COPY --from=build /tmp/target/*.jar /app/zadatak_za_programiranje.jar
EXPOSE 8080
ENTRYPOINT ["java","-Dspring.profiles.active=production","-jar","/app/zadatak_za_programiranje.jar"]